# Generated by Django 5.2.6 on 2025-10-22 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(help_text='Full name of the faculty', max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'ordering': ['faculty_name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(help_text='Name of the zone (e.g., Main Campus)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the zone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['zone_name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(help_text='Name of the section (e.g., Science Building)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of the section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(help_text='The zone this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cleaning.zone')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['zone', 'section_name'],
                'unique_together': {('zone', 'section_name')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(help_text='Name of the unit (e.g., Lecture Hall 1)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of the unit')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this unit is currently in use or under maintenance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(blank=True, help_text='The faculty responsible for this unit (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='cleaning.faculty')),
                ('section', models.ForeignKey(blank=True, help_text='The section this unit belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='cleaning.section')),
                ('zone', models.ForeignKey(help_text='The zone this unit belongs to (required)', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='cleaning.zone')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['zone', 'unit_name'],
                'unique_together': {('zone', 'unit_name')},
            },
        ),
    ]
