# Generated by Django 5.2.6 on 2025-10-24 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified')], default='PENDING', help_text='Current status of the cleaning task', max_length=20)),
                ('scheduled_date', models.DateField(help_text='Date when cleaning is scheduled')),
                ('scheduled_time', models.TimeField(help_text='Time when cleaning is scheduled')),
                ('completed_date', models.DateTimeField(blank=True, help_text='Date and time when cleaning was completed', null=True)),
                ('verified_date', models.DateTimeField(blank=True, help_text='Date and time when cleaning was verified', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations')),
                ('verification_notes', models.TextField(blank=True, help_text='Notes added by manager during verification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='The assistant assigned to clean this unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cleaning_records', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(help_text='The unit that was cleaned', on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_records', to='cleaning.unit')),
                ('verified_by', models.ForeignKey(blank=True, help_text='The manager who verified this cleaning', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cleaning_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cleaning Record',
                'verbose_name_plural': 'Cleaning Records',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
    ]
