# Generated by Django 5.2.7 on 2025-10-24 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0002_cleaningrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(help_text='Name of the cleaning activity (e.g., Sweep floor, Mop floor)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the activity')),
                ('frequency', models.CharField(choices=[('TWICE_DAILY', 'Twice Per Day'), ('DAILY', 'Daily'), ('EVERY_2_DAYS', 'Every 2 Days'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Every 2 Weeks'), ('MONTHLY', 'Monthly')], default='DAILY', help_text='How often this activity should be performed', max_length=20)),
                ('estimated_duration', models.PositiveIntegerField(default=30, help_text='Estimated time to complete in minutes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this activity is currently required')),
                ('special_instructions', models.TextField(blank=True, help_text='Special instructions or requirements for this activity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(help_text='The unit this activity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_activities', to='cleaning.unit')),
            ],
            options={
                'verbose_name': 'Cleaning Activity',
                'verbose_name_plural': 'Cleaning Activities',
                'ordering': ['unit', 'activity_name'],
                'unique_together': {('unit', 'activity_name')},
            },
        ),
        migrations.AddField(
            model_name='cleaningrecord',
            name='activity',
            field=models.ForeignKey(blank=True, help_text='The specific activity performed (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_records', to='cleaning.cleaningactivity'),
        ),
    ]
