# Generated by Django 5.2.7 on 2025-10-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0004_fix_activity_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningactivity',
            name='estimated_duration',
        ),
    ]
