# Generated by Django 5.2.7 on 2025-10-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0005_remove_cleaningactivity_estimated_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningrecord',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Time when cleaning is scheduled (optional)', null=True),
        ),
    ]
