# Generated by Django 5.2.7 on 2025-10-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0006_alter_cleaningrecord_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningactivity',
            name='cleaning_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional: Target month (1-12) for planning this activity', null=True),
        ),
        migrations.AddField(
            model_name='cleaningactivity',
            name='cleaning_year',
            field=models.PositiveIntegerField(blank=True, help_text='Optional: Target year for planning this activity', null=True),
        ),
    ]
