# Generated by Django 5.2.6 on 2025-10-25 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0007_cleaningactivity_cleaning_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningactivity',
            name='cleaning_month',
        ),
        migrations.RemoveField(
            model_name='cleaningactivity',
            name='cleaning_year',
        ),
        migrations.AddField(
            model_name='cleaningactivity',
            name='budget_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Budget working percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
