# Generated by Django 5.2.6 on 2025-10-26 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0008_remove_cleaningactivity_cleaning_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Zone this faculty belongs to (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faculties', to='cleaning.zone'),
        ),
    ]
