# Generated by Django 5.2.7 on 2025-10-27 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0009_faculty_zone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='assigned_assistant',
            field=models.ForeignKey(blank=True, help_text='The assistant assigned to clean this unit (optional)', limit_choices_to={'role': 'ASSISTANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_units', to=settings.AUTH_USER_MODEL),
        ),
    ]
