# Generated by Django 5.2.6 on 2025-10-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('ASSISTANT', 'Assistant'), ('DEAN_OFFICE', 'Dean Office')], default='ASSISTANT', help_text='User role in the system', max_length=15),
        ),
    ]
