# Generated by Django 5.2.7 on 2025-10-26 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('cleaning', '0009_faculty_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Faculty this dean office user is associated with (for DEAN_OFFICE role)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_users', to='cleaning.faculty'),
        ),
    ]
